### model
model_name_or_path: /zfsauton2/home/wentsec/Meta-Llama-3.1-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: babyai
template: llama3
cutoff_len: 1024
max_samples: 5120
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: /dev/shm/fine_tuned_models/fft
resume_from_checkpoint: /dev/shm/fine_tuned_models/fft/checkpoint
logging_steps: 1
save_steps: 20
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

# ### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
